
import "./globals.css";
import MyThirdwebProvider from "./components/provider/MyThirdwebProvider";
import { StateContextProvider } from "./context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MyThirdwebProvider>
          <StateContextProvider>
            {children}
          </StateContextProvider>
        </MyThirdwebProvider>
      </body>
    </html>
  );
}
